$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), %w[lib]))

require '_APPLICATION_DOWNCODE_'

namespace :_APPLICATION_DOWNCODE_ do

  namespace :process do

    desc 'Create console'
    task :console do |task|
      system('bundle exec irb -r ./console.rb --back-trace-limit 100')
    end

    namespace :server do

      desc 'Start the server'
      task :start, [:daemonize] => ['_APPLICATION_DOWNCODE_:cache:destroy'] do |task, arguments|
        daemonize = arguments.daemonize ? arguments.daemonize.to_b : true
        puts "Starting ..."
        system("mkdir -p ./process/thin/log ./process/thin/pid; bundle exec thin --rackup configuration.ru --port 8000 --log ./process/thin/log/thin.log --pid ./process/thin/pid/thin.pid #{daemonize ? '--daemonize' : nil} start")
      end

      desc 'Stop the server'
      task :stop do |task|
        puts "Stopping ..."
        system('for pid in ./process/thin/pid/*.pid; do bundle exec thin --pid $pid stop; done')
      end

      desc 'Restart the server'
      task :restart => ['_APPLICATION_DOWNCODE_:process:server:stop',
                        '_APPLICATION_DOWNCODE_:process:server:start']

    end

  end

  namespace :cache do

    desc 'List all cached files'
    task :list do
      system('find . | grep \'\\.cache\'')
    end

    desc 'Remove all cached files'
    task :destroy do
      system('find . -name \'.cache\' | xargs rm -rv')
    end

  end

end
