require 'ruby_app/mixins/array_extension'
require 'ruby_app/mixins/class_extension'
require 'ruby_app/mixins/object_extension'
require 'ruby_app/mixins/string_extension'

require 'ruby_app/mixins/configuration_mixin'
require 'ruby_app/mixins/delegate_mixin'
require 'ruby_app/mixins/hash_mixin'
require 'ruby_app/mixins/render_mixin'
require 'ruby_app/mixins/route_mixin'
require 'ruby_app/mixins/template_mixin'
require 'ruby_app/mixins/translate_mixin'
