load_script! 'features/authentications/facebook'
load_script! 'features/authentications/o_auth/git_hub'
load_script! 'features/authentications/open_id/google'
load_script! 'features/authentications/open_id/my_open_id'
load_script! 'features/authentications/open_id/yahoo'
